AllCops:
  Exclude:
    - passman.gemspec
    - bin/passman
    - bin/passman-cli

Documentation:
  Enabled: false

LineLength:
  Max: 99

FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

Rails/Blank:
  Enabled: false
