language: ruby
rvm:
  - 2.0.0
  - 2.1
  - 2.2
  - 2.2.4
  - 2.3.0

install:
  - gem install bundler
  - bundle install --retry=3

script:
  - bundle exec rspec
  - bundle exec rubocop -R --format simple

os:
  - linux
  - osx

matrix:
  exclude:
    - rvm: 1.9.3
      os: osx
    - rvm: 2.2
      os: osx
    - rvm: 2.2.4
      os: osx
    - rvm: 2.3.0
      os: osx
